---

- name: restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true

- name: reload syslogd
  ansible.builtin.service:
    name: syslogd
    state: reloaded
  become: true
