---

- name: restart-sssd
  ansible.builtin.service:
    name: sssd
    state: restarted
    enabled: true

- name: restart-sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: rehash-certs
  ansible.builtin.command: certctl rehash
  changed_when: false
