---

- name: restart-sssd
  ansible.builtin.service:
    name: sssd
    enabled: true
    state: restarted

- name: restart-ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: update-ca-trust
  ansible.builtin.command: update-ca-trust
  changed_when: false
